version: '3.4'
services:
  freedns_updator:
    container_name: freedns_updater
    image: notquitenothing/freedns_updater:latest
    restart: unless-stopped
    environment:
      TOKENS: "randomizedToken1; randomizedToken2; ..." #provided by the afraid.org version 2 dynamic update interface
      HOURS_INTERVAL: "1" #optional, defaults to each hour
      MINS_INTERVAL: "20" #optional, default 20 mins
